name: Build final PDF
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Satzung.tex'
      - 'Hintergrund_Inhaltsseite.pdf'
      - 'Hintergrund_Titelseite.pdf'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.GH_PAT }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Satzung.tex
          latexmk_use_xelatex: true
          extra_fonts: 'fonts/*.ttf'
      - name: Commit PDF
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add Satzung.pdf
          git commit -m "Automatisches Update von Satzung.pdf"
          git push
