name: Build LaTeX document
on: pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.GH_PAT }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Satzung.tex
          latexmk_use_xelatex: true
          extra_fonts: 'fonts/*.ttf'
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Satzung.pdf
